#ASSIGMENT THE FIRST WORD TO THE VARIABLE WORD1
word1 = "coding"

#ASSIGMENT THE FIRST WORD TO THE VARIABLE WORD2
word2 = "is"

#ASSIGMENT THE FIRST WORD TO THE VARIABLE  WORD3
word3 = "cool"
c = word1 + " " + word2 + "  " + word3
print(c)


